# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/14b524b1-8136-4ced-b515-a26dbe20ff5e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."crypt-root".device = "/dev/disk/by-uuid/20b52fdc-a137-4b56-ba80-cead63530624";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/22d52bc4-aba1-4be2-913b-d82b2dc63204";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fd88947a-5d73-43a0-9ddf-494effbaf313"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
